# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-12 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
